"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-mjwz#4z1bx5w^*6u2)8y8+)bt+1k00!rx07(@pe8fesqlls81m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_ckeditor_5',
    #'admin_honeypot',
    'healthcenter',
    'accounts',
    'crispy_forms',
    'crispy_bootstrap5',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# Authentication Settings
LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'healthcenter:home'
LOGOUT_REDIRECT_URL = 'accounts:login'

# Session Security Settings
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds

# Security Settings
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_CONTENT_TYPE_NOSNIFF = True

# CKEditor 5 Configuration
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_UPLOAD_PATH = "uploads/"

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', '|', 'fontSize', 'fontColor', '|', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', '|', 'alignment', '|', 'sourceEditing', 'insertTable', 'mediaEmbed', 'undo', 'redo', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        'language': 'en',
    },
    'extends': { # An example config for more features
        'toolbar': ['heading', '|', 'bold', 'italic', '|', 'fontSize', 'fontColor', '|', 'link', 'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', '|', 'alignment', '|', 'sourceEditing', 'insertTable', 'mediaEmbed', 'undo', 'redo', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
        'language': 'en',
    },
    # You can define multiple configurations and reference them in your model field
}

# --- 3. CKEDITOR 5 CONFIGURATION (CKEDITOR_5_CONFIGS) ---
# CKEDITOR_5_CONFIGS = {
#     'default': {
#         # CORE PLUGINS: Add FontColor and FontSize
#         'plugins': [
#             'Alignment', 'AutoImage', 'AutoLink', 'BlockQuote', 'Bold', 'Code', 'CodeBlock', 
#             'Essentials', 'FontColor', 'FontSize', 'Heading', 'Image', 'ImageCaption', 
#             'ImageStyle', 'ImageToolbar', 'Indent', 'Italic', 'Link', 'List', 'MediaEmbed', 
#             'Paragraph', 'PasteFromOffice', 'Table', 'TableToolbar', 'TextTransformation', 
#             'Undo', 'Redo'
#         ],
#         # TOOLBAR SETUP: Add fontColor and fontSize buttons
#         'toolbar': [
#             'heading', '|', 'bold', 'italic', 'link', 'bulletedList', 'numberedList', 
#             '|', 'fontSize', 'fontColor', '|',  # <-- FONT FEATURES ADDED HERE
#             'blockQuote', 'codeBlock', 'insertTable', 'imageUpload', 'mediaEmbed', '|', 
#             'undo', 'redo'
#         ],
#         # IMAGE CONFIG: Recommended for image handling
#         'image': {
#             'toolbar': ['imageTextAlternative', 'toggleImageCaption', 'imageStyle:inline', 'imageStyle:block', 'imageStyle:side'],
#             'upload': {'types': ['webp', 'jpeg', 'png', 'gif', 'bmp', 'tiff', 'svg', 'jpg', 'jiff']}
#         },
#         # ALLOW HTML STYLES: Necessary for font size/color to persist
#         'htmlSupport': {
#             'allow:': [{'name': '__ANY__', 'attributes': True, 'classes': True, 'styles': True}]
#         },
#         'menuBar': {
#             'isVisible': True
#         },
#     },
#     # You can define other configurations (e.g., 'simple') here
# }

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"