# Generated by Django 5.2.8 on 2025-11-30 04:12

import django_ckeditor_5.fields
import healthcenter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Mission')),
                ('vision', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Vision')),
                ('history', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='History')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description')),
                ('established_year', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Address')),
                ('working_hours', django_ckeditor_5.fields.CKEditor5Field(help_text='e.g., Mon-Fri: 8:00 AM - 4:30 PM', verbose_name='Working Hours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('body', django_ckeditor_5.fields.CKEditor5Field(validators=[healthcenter.validators.validate_no_sql_injection], verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content',
                'verbose_name_plural': 'Contents',
            },
        ),
    ]
