# Generated by Django 5.2.8 on 2025-11-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Mark as active/published'),
        ),
    ]
