# Generated by Django 5.2.8 on 2025-11-30 13:13

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0002_about_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=200)),
                ('banner_image_1', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('banner_image_2', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('banner_image_3', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('banner_description_1', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_description_2', models.CharField(blank=True, max_length=500, null=True)),
                ('banner_description_3', models.CharField(blank=True, max_length=500, null=True)),
                ('welcome_message', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Welcome Message')),
                ('short_description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Short Description')),
                ('vision', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Vision')),
                ('mission', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Mission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/')),
            ],
            options={
                'verbose_name': 'Home Page',
                'verbose_name_plural': 'Home Page',
            },
        ),
        migrations.AddField(
            model_name='about',
            name='banner_description_1',
            field=models.CharField(blank=True, help_text='Banner description 1', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_description_2',
            field=models.CharField(blank=True, help_text='Banner description 2', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_description_3',
            field=models.CharField(blank=True, help_text='Banner description 3', max_length=300),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='banner_images/'),
        ),
        migrations.AddField(
            model_name='about',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Banner title for homepage', max_length=200),
        ),
        migrations.AddField(
            model_name='about',
            name='short_description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Short Description'),
        ),
        migrations.AddField(
            model_name='about',
            name='welcome_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Welcome Message'),
        ),
    ]
