# Generated by Django 5.2.8 on 2025-11-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthcenter', '0003_home_about_banner_description_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='video_embed',
            field=models.TextField(blank=True, help_text='Paste embed code or video URL here', null=True),
        ),
    ]
